# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/pytrim2',
                'doc_host': 'https://hcstubbe.github.io',
                'git_url': 'https://github.com/hcstubbe/pytrim2',
                'lib_path': 'pytrim2'},
  'syms': { 'pytrim2.core': { 'pytrim2.core.align_barcodes': ('core.html#align_barcodes', 'pytrim2/core.py'),
                              'pytrim2.core.decide_barcode_id': ('core.html#decide_barcode_id', 'pytrim2/core.py'),
                              'pytrim2.core.demultiplex': ('core.html#demultiplex', 'pytrim2/core.py'),
                              'pytrim2.core.findAlingments': ('core.html#findalingments', 'pytrim2/core.py'),
                              'pytrim2.core.sort_records_to_file': ('core.html#sort_records_to_file', 'pytrim2/core.py'),
                              'pytrim2.core.trim_record': ('core.html#trim_record', 'pytrim2/core.py')}}}