# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/pytrim2',
                'doc_host': 'https://hcstubbe.github.io',
                'git_url': 'https://github.com/hcstubbe/pytrim2',
                'lib_path': 'pytrim2'},
  'syms': {'pytrim2.core': {'pytrim2.core.foo': ('core.html#foo', 'pytrim2/core.py')}}}