# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/pytrim2',
                'doc_host': 'https://hcstubbe.github.io',
                'git_url': 'https://github.com/hcstubbe/pytrim2',
                'lib_path': 'pytrim2'},
  'syms': { 'pytrim2.core': {'pytrim2.core.foo': ('core.html#foo', 'pytrim2/core.py')},
            'pytrim2.pytrim2.core': { 'pytrim2.pytrim2.core.align_barcodes': ( 'pytrim2/core.html#align_barcodes',
                                                                               'pytrim2/pytrim2/core.py'),
                                      'pytrim2.pytrim2.core.decide_barcode_id': ( 'pytrim2/core.html#decide_barcode_id',
                                                                                  'pytrim2/pytrim2/core.py'),
                                      'pytrim2.pytrim2.core.demultiplex': ('pytrim2/core.html#demultiplex', 'pytrim2/pytrim2/core.py'),
                                      'pytrim2.pytrim2.core.findAlingments': ( 'pytrim2/core.html#findalingments',
                                                                               'pytrim2/pytrim2/core.py'),
                                      'pytrim2.pytrim2.core.sort_records_to_file': ( 'pytrim2/core.html#sort_records_to_file',
                                                                                     'pytrim2/pytrim2/core.py'),
                                      'pytrim2.pytrim2.core.trim_record': ('pytrim2/core.html#trim_record', 'pytrim2/pytrim2/core.py')},
            'pytrim2.setup': {}}}